#!/bin/bash

# PulseAudio volume changer and osd for notify-osd
# depends on: notify-osd, pulseaudio
# v1.1 by sen

# -- config --
VOLUME_SAVE="/dev/shm/saved_vol"
STEP=5
VOLUME=$(( $(pacmd dump |grep set-sink-volume |cut -d" " -f3) / 655 ))
DEVICE=$(pacmd dump |grep "set-sink-volume" |cut -d" " -f2)


# -- increase volume --
if [[ $1 = '-i' ]] && [[ VOLUME -lt 100 ]]; then
	if [[ VOLUME+STEP -lt 100 ]]; then
		VOLUME=$((VOLUME+STEP))
	else
		VOLUME=100
	fi
# -- decrease volume --
elif [[ $1 = '-d' ]]&& [[ VOLUME -gt 0 ]]; then
	if [[ VOLUME-STEP -gt 0 ]]; then
		VOLUME=$((VOLUME-STEP))
	else
		VOLUME=0
	fi
# -- toggle mute --
elif [[ $1 = '-t' ]]; then
	if [[ ! -d $VOLUME_SAVE ]]; then
		touch $VOLUME_SAVE
	fi
	if [[ VOLUME -eq 0 ]]; then
		VOLUME=$(cat $VOLUME_SAVE)
	else
		echo $VOLUME >| $VOLUME_SAVE
		VOLUME=0
	fi
else
    exit 1
fi
SET=$((VOLUME*655))
pacmd set-sink-volume $DEVICE $SET > /dev/null

# -- notify-osd --
if [[ VOLUME -eq 0 ]]; then
	ICON=notification-audio-volume-muted
else
	if [[ VOLUME -lt 25 ]]; then
		ICON=notification-audio-volume-off
	elif [[ VOLUME -lt 50 ]]; then
		ICON=notification-audio-volume-low
	elif [[ VOLUME -lt 75 ]]; then
		ICON=notification-audio-volume-medium
	else
		ICON=notification-audio-volume-high
	fi
fi
notify-send "Volume" -i $ICON -h int:value:$VOLUME -h string:x-canonical-private-synchronous:1
